spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_led_outdoor_bd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true